/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Item, ItemType, TileType, WallType, Recipe } from './types';

export const ITEMS: Record<string, Item> = {
  // Tools
  copper_pickaxe: {
    id: 'copper_pickaxe',
    name: 'Copper Pickaxe',
    type: ItemType.Tool,
    description: 'Used to mine blocks. Fairly slow.',
    damage: 4,
    range: 5,
    miningSpeed: 1.0,
    maxStack: 1,
    spriteColor: '#B87333',
    spriteChar: '⛏️',
  },
  gold_pickaxe: {
    id: 'gold_pickaxe',
    name: 'Gold Pickaxe',
    type: ItemType.Tool,
    description: 'Mines blocks significantly faster.',
    damage: 6,
    range: 6,
    miningSpeed: 0.6,
    maxStack: 1,
    spriteColor: '#FFD700',
    spriteChar: '⛏️',
  },
  platinum_pickaxe: {
    id: 'platinum_pickaxe',
    name: 'Platinum Pickaxe',
    type: ItemType.Tool,
    description: 'An elite pickaxe. Can mine ebonstone easily!',
    damage: 8,
    range: 7,
    miningSpeed: 0.4,
    maxStack: 1,
    spriteColor: '#E5E4E2',
    spriteChar: '⛏️',
  },
  copper_axe: {
    id: 'copper_axe',
    name: 'Copper Axe',
    type: ItemType.Tool,
    description: 'Used to chop down trees.',
    damage: 3,
    range: 5,
    miningSpeed: 1.0, // Axe speed
    maxStack: 1,
    spriteColor: '#B87333',
    spriteChar: '🪓',
  },

  // Weapons
  wooden_sword: {
    id: 'wooden_sword',
    name: 'Wooden Sword',
    type: ItemType.Weapon,
    description: 'A basic weapon made of wood.',
    damage: 7,
    knockback: 4,
    range: 3.5,
    maxStack: 1,
    spriteColor: '#8B5A2B',
    spriteChar: '🗡️',
  },
  gold_broadsword: {
    id: 'gold_broadsword',
    name: 'Gold Broadsword',
    type: ItemType.Weapon,
    description: 'A shiny broadsword with high damage and swing range.',
    damage: 15,
    knockback: 6,
    range: 4.5,
    maxStack: 1,
    spriteColor: '#FFD700',
    spriteChar: '⚔️',
  },
  fiery_greatsword: {
    id: 'fiery_greatsword',
    name: 'Fiery Greatsword',
    type: ItemType.Weapon,
    description: 'A massive blade forged in caverns. Sparkles with embers!',
    damage: 26,
    knockback: 8,
    range: 5.5,
    maxStack: 1,
    spriteColor: '#FF4500',
    spriteChar: '🔥',
  },
  wooden_bow: {
    id: 'wooden_bow',
    name: 'Wooden Bow',
    type: ItemType.Weapon,
    description: 'Fires wooden arrows. Keeps monsters at a distance!',
    damage: 9,
    range: 12,
    maxStack: 1,
    spriteColor: '#A0522D',
    spriteChar: '🏹',
  },
  starfury: {
    id: 'starfury',
    name: 'Starfury',
    type: ItemType.Weapon,
    description: 'Rain down stars from the heavens upon your enemies!',
    damage: 22,
    knockback: 5,
    range: 6.0,
    maxStack: 1,
    spriteColor: '#1E90FF',
    spriteChar: '💫',
  },

  // Ammo & Projectiles
  wooden_arrow: {
    id: 'wooden_arrow',
    name: 'Wooden Arrow',
    type: ItemType.Material,
    description: 'Ammunition for bows.',
    maxStack: 250,
    spriteColor: '#CD853F',
    spriteChar: '➔',
  },

  // Blocks
  dirt_block: {
    id: 'dirt_block',
    name: 'Dirt Block',
    type: ItemType.Block,
    description: 'Simple soil. Can grow grass when exposed to sky.',
    tileType: TileType.Dirt,
    maxStack: 999,
    spriteColor: '#5C4033',
    spriteChar: '🟫',
  },
  stone_block: {
    id: 'stone_block',
    name: 'Stone Block',
    type: ItemType.Block,
    description: 'Hard rock. Used for walls and crafting.',
    tileType: TileType.Stone,
    maxStack: 999,
    spriteColor: '#808080',
    spriteChar: '⬜',
  },
  wood_block: {
    id: 'wood_block',
    name: 'Wood Block',
    type: ItemType.Block,
    description: 'Sturdy timber. Good for building houses.',
    tileType: TileType.Wood,
    maxStack: 999,
    spriteColor: '#8B5A2B',
    spriteChar: '🪵',
  },
  sand_block: {
    id: 'sand_block',
    name: 'Sand Block',
    type: ItemType.Block,
    description: 'Loose granular desert sand.',
    tileType: TileType.Sand,
    maxStack: 999,
    spriteColor: '#EDC9AF',
    spriteChar: '🟨',
  },
  clay_block: {
    id: 'clay_block',
    name: 'Clay Block',
    type: ItemType.Block,
    description: 'Sticky red clay. Can be baked into bricks.',
    tileType: TileType.Clay,
    maxStack: 999,
    spriteColor: '#B22222',
    spriteChar: '🧱',
  },
  brick_block: {
    id: 'brick_block',
    name: 'Clay Brick',
    type: ItemType.Block,
    description: 'Finely baked building bricks.',
    tileType: TileType.Brick,
    maxStack: 999,
    spriteColor: '#CD5C5C',
    spriteChar: '🧱',
  },
  ebonstone_block: {
    id: 'ebonstone_block',
    name: 'Ebonstone Block',
    type: ItemType.Block,
    description: 'Incredibly hard purple rock infected by the corruption.',
    tileType: TileType.Ebonstone,
    maxStack: 999,
    spriteColor: '#4B0082',
    spriteChar: '🟪',
  },
  wood_platform: {
    id: 'wood_platform',
    name: 'Wooden Platform',
    type: ItemType.Block,
    description: 'A ledge that can be climbed on. Drop through with [S] or [Down].',
    tileType: TileType.Platform,
    maxStack: 999,
    spriteColor: '#D2B48C',
    spriteChar: '▬',
  },
  torch: {
    id: 'torch',
    name: 'Torch',
    type: ItemType.Block,
    description: 'Emits a bright, comforting light.',
    tileType: TileType.Torch,
    maxStack: 99,
    spriteColor: '#FFD700',
    spriteChar: '🕯️',
  },

  // Furniture / Stations
  workbench: {
    id: 'workbench',
    name: 'Work Bench',
    type: ItemType.Block,
    description: 'Required for basic crafting recipes.',
    tileType: TileType.Workbench,
    maxStack: 9,
    spriteColor: '#DEB887',
    spriteChar: '🪑',
  },
  anvil: {
    id: 'anvil',
    name: 'Iron Anvil',
    type: ItemType.Block,
    description: 'Used to forge metal gear from ore bars.',
    tileType: TileType.Anvil,
    maxStack: 9,
    spriteColor: '#4F4F4F',
    spriteChar: '⚓',
  },
  chest: {
    id: 'chest',
    name: 'Wooden Chest',
    type: ItemType.Block,
    description: 'Place it and interact with [Right-Click] to store your loot!',
    tileType: TileType.Chest,
    maxStack: 9,
    spriteColor: '#CD853F',
    spriteChar: '🧰',
  },

  // Walls
  dirt_wall: {
    id: 'dirt_wall',
    name: 'Dirt Wall',
    type: ItemType.Wall,
    description: 'Background wall. Stops monster spawning in houses.',
    wallType: WallType.DirtWall,
    maxStack: 999,
    spriteColor: '#453026',
    spriteChar: '░',
  },
  wood_wall: {
    id: 'wood_wall',
    name: 'Wood Wall',
    type: ItemType.Wall,
    description: 'Cozy background wall for houses.',
    wallType: WallType.WoodWall,
    maxStack: 999,
    spriteColor: '#6B4226',
    spriteChar: '▒',
  },
  stone_wall: {
    id: 'stone_wall',
    name: 'Stone Wall',
    type: ItemType.Wall,
    description: 'Durable background stone wall.',
    wallType: WallType.StoneWall,
    maxStack: 999,
    spriteColor: '#555555',
    spriteChar: '▓',
  },

  // Materials
  gel: {
    id: 'gel',
    name: 'Slime Gel',
    type: ItemType.Material,
    description: 'Sticky gelatinous slime. Smells like pine needles.',
    maxStack: 999,
    spriteColor: '#00FFFF',
    spriteChar: '💧',
  },
  wood: {
    id: 'wood',
    name: 'Wood',
    type: ItemType.Material,
    description: 'Raw lumber harvested from trees.',
    maxStack: 999,
    spriteColor: '#8B5A2B',
    spriteChar: '🪵',
  },
  stone: {
    id: 'stone',
    name: 'Stone',
    type: ItemType.Material,
    description: 'Raw stone mined from the caverns.',
    maxStack: 999,
    spriteColor: '#808080',
    spriteChar: '🪨',
  },
  iron_ore: {
    id: 'iron_ore',
    name: 'Iron Ore',
    type: ItemType.Material,
    description: 'A rusty metal ore. Can be melted down.',
    maxStack: 999,
    spriteColor: '#D2691E',
    spriteChar: '🟫',
  },
  iron_bar: {
    id: 'iron_bar',
    name: 'Iron Bar',
    type: ItemType.Material,
    description: 'Smelted iron bar. Used for smithing.',
    maxStack: 99,
    spriteColor: '#C0C0C0',
    spriteChar: '🪙',
  },
  gold_ore: {
    id: 'gold_ore',
    name: 'Gold Ore',
    type: ItemType.Material,
    description: 'Valuable shimmering ore.',
    maxStack: 999,
    spriteColor: '#FFD700',
    spriteChar: '🟡',
  },
  gold_bar: {
    id: 'gold_bar',
    name: 'Gold Bar',
    type: ItemType.Material,
    description: 'Pure smelted gold. Used for premium gear.',
    maxStack: 99,
    spriteColor: '#FFDF00',
    spriteChar: '🟨',
  },
  lens: {
    id: 'lens',
    name: 'Lens',
    type: ItemType.Material,
    description: 'Dropped by Demon Eyes. Reflects spooky light.',
    maxStack: 99,
    spriteColor: '#ADD8E6',
    spriteChar: '👁️',
  },
  fallen_star: {
    id: 'fallen_star',
    name: 'Fallen Star',
    type: ItemType.Material,
    description: 'Fell from the cosmos. Disappears at dawn.',
    maxStack: 99,
    spriteColor: '#FFFF00',
    spriteChar: '⭐',
  },

  // Consumables / Potions
  mushroom: {
    id: 'mushroom',
    name: 'Mushroom',
    type: ItemType.Consumable,
    description: 'A small red-capped mushroom. Eat it directly.',
    healPower: 20,
    maxStack: 99,
    spriteColor: '#FF0000',
    spriteChar: '🍄',
  },
  lesser_healing_potion: {
    id: 'lesser_healing_potion',
    name: 'Lesser Healing Potion',
    type: ItemType.Consumable,
    description: 'Restores a moderate amount of health. Cooldown of 15 seconds.',
    healPower: 70,
    maxStack: 30,
    spriteColor: '#FF6347',
    spriteChar: '🧪',
  },
  suspicious_looking_eye: {
    id: 'suspicious_looking_eye',
    name: 'Suspicious Looking Eye',
    type: ItemType.Consumable,
    description: 'Summons the Eye of Cthulhu at night! Use with absolute caution.',
    maxStack: 5,
    spriteColor: '#EE82EE',
    spriteChar: '👁️',
  },

  // Accessories
  hermes_boots: {
    id: 'hermes_boots',
    name: 'Hermes Boots',
    type: ItemType.Accessory,
    description: 'Equip: Increases maximum running speed by 50%!',
    maxStack: 1,
    spriteColor: '#32CD32',
    spriteChar: '🥾',
    isAccessory: true,
  },
  cloud_in_a_bottle: {
    id: 'cloud_in_a_bottle',
    name: 'Cloud in a Bottle',
    type: ItemType.Accessory,
    description: 'Equip: Grants the user a double jump!',
    maxStack: 1,
    spriteColor: '#F0F8FF',
    spriteChar: '☁️',
    isAccessory: true,
  },
  band_of_regeneration: {
    id: 'band_of_regeneration',
    name: 'Band of Regeneration',
    type: ItemType.Accessory,
    description: 'Equip: Slowly regenerates 1 Health Point per second.',
    maxStack: 1,
    spriteColor: '#FF1493',
    spriteChar: '💍',
    isAccessory: true,
  },
};

export const RECIPES: Recipe[] = [
  // Basic hand crafting
  {
    id: 'torch_craft',
    result: { item: ITEMS.torch, count: 3 },
    ingredients: [
      { itemId: 'wood', count: 1 },
      { itemId: 'gel', count: 1 },
    ],
  },
  {
    id: 'workbench_craft',
    result: { item: ITEMS.workbench, count: 1 },
    ingredients: [{ itemId: 'wood', count: 10 }],
  },
  {
    id: 'wood_platform_craft',
    result: { item: ITEMS.wood_platform, count: 2 },
    ingredients: [{ itemId: 'wood', count: 1 }],
  },

  // Workbench crafting
  {
    id: 'wooden_sword_craft',
    result: { item: ITEMS.wooden_sword, count: 1 },
    ingredients: [{ itemId: 'wood', count: 7 }],
    requiresStation: TileType.Workbench,
  },
  {
    id: 'wooden_bow_craft',
    result: { item: ITEMS.wooden_bow, count: 1 },
    ingredients: [{ itemId: 'wood', count: 10 }],
    requiresStation: TileType.Workbench,
  },
  {
    id: 'wooden_arrow_craft',
    result: { item: ITEMS.wooden_arrow, count: 10 },
    ingredients: [
      { itemId: 'wood', count: 1 },
      { itemId: 'stone', count: 1 },
    ],
    requiresStation: TileType.Workbench,
  },
  {
    id: 'wood_wall_craft',
    result: { item: ITEMS.wood_wall, count: 4 },
    ingredients: [{ itemId: 'wood', count: 1 }],
    requiresStation: TileType.Workbench,
  },
  {
    id: 'stone_wall_craft',
    result: { item: ITEMS.stone_wall, count: 4 },
    ingredients: [{ itemId: 'stone', count: 1 }],
    requiresStation: TileType.Workbench,
  },
  {
    id: 'dirt_wall_craft',
    result: { item: ITEMS.dirt_wall, count: 4 },
    ingredients: [{ itemId: 'dirt_block', count: 1 }],
    requiresStation: TileType.Workbench,
  },
  {
    id: 'clay_brick_craft',
    result: { item: ITEMS.brick_block, count: 1 },
    ingredients: [{ itemId: 'clay_block', count: 2 }],
    requiresStation: TileType.Workbench,
  },
  {
    id: 'chest_craft',
    result: { item: ITEMS.chest, count: 1 },
    ingredients: [
      { itemId: 'wood', count: 8 },
      { itemId: 'iron_bar', count: 2 },
    ],
    requiresStation: TileType.Workbench,
  },
  {
    id: 'anvil_craft',
    result: { item: ITEMS.anvil, count: 1 },
    ingredients: [{ itemId: 'iron_bar', count: 5 }],
    requiresStation: TileType.Workbench,
  },

  // Smithy / Anvil crafting
  {
    id: 'iron_bar_craft',
    result: { item: ITEMS.iron_bar, count: 1 },
    ingredients: [{ itemId: 'iron_ore', count: 3 }],
    requiresStation: TileType.Anvil, // In real game it's furnace, but anvil simplifies/condenses stations beautifully
  },
  {
    id: 'gold_bar_craft',
    result: { item: ITEMS.gold_bar, count: 1 },
    ingredients: [{ itemId: 'gold_ore', count: 4 }],
    requiresStation: TileType.Anvil,
  },
  {
    id: 'gold_pickaxe_craft',
    result: { item: ITEMS.gold_pickaxe, count: 1 },
    ingredients: [
      { itemId: 'gold_bar', count: 8 },
      { itemId: 'wood', count: 4 },
    ],
    requiresStation: TileType.Anvil,
  },
  {
    id: 'platinum_pickaxe_craft',
    result: { item: ITEMS.platinum_pickaxe, count: 1 },
    ingredients: [
      { itemId: 'gold_bar', count: 12 }, // proxy for platinum
      { itemId: 'iron_bar', count: 4 },
    ],
    requiresStation: TileType.Anvil,
  },
  {
    id: 'gold_sword_craft',
    result: { item: ITEMS.gold_broadsword, count: 1 },
    ingredients: [
      { itemId: 'gold_bar', count: 8 },
      { itemId: 'wood', count: 3 },
    ],
    requiresStation: TileType.Anvil,
  },
  {
    id: 'fiery_greatsword_craft',
    result: { item: ITEMS.fiery_greatsword, count: 1 },
    ingredients: [
      { itemId: 'gold_bar', count: 10 },
      { itemId: 'stone', count: 20 },
      { itemId: 'gel', count: 15 },
    ],
    requiresStation: TileType.Anvil,
  },
  {
    id: 'suspicious_eye_craft',
    result: { item: ITEMS.suspicious_looking_eye, count: 1 },
    ingredients: [{ itemId: 'lens', count: 6 }],
    requiresStation: TileType.Workbench,
  },
  {
    id: 'potion_craft',
    result: { item: ITEMS.lesser_healing_potion, count: 1 },
    ingredients: [
      { itemId: 'mushroom', count: 1 },
      { itemId: 'gel', count: 2 },
    ],
    requiresStation: TileType.Workbench,
  },
];

// Guide NPC tips
export const GUIDE_TIPS = [
  "Welcome to the 2D Pixel Sandbox! You can move around with [A][D] or [Left][Right], and jump with [Space] or [W].",
  "To mine tiles, select your Copper Pickaxe in your hotbar, then click and hold on a nearby block. Make sure you are standing close enough!",
  "Gather Wood from trees and Gel from Slimes. You can combine them in your inventory to craft Torches! Torches light up the dark caverns.",
  "Build a house! A valid house needs a floor, walls made of blocks, background walls (like Wood Walls), a door, and a Torch. The Guide (me!) will move in.",
  "Build a Work Bench! Having one placed nearby will unlock a ton of new crafting recipes like Swords, Bows, and Doors.",
  "At night, dangerous Zombies and Demon Eyes spawn. Stay inside or craft a Wooden Sword to defend yourself!",
  "If you find Iron Ore and Gold Ore deep underground, build an Iron Anvil to forge them into bars and craft high-grade weapons and armor.",
  "Search chests in caves! You might find rare accessories like Hermes Boots (run faster) or Cloud in a Bottle (double jump!).",
  "Gather Lenses from Demon Eyes at night. If you collect 6 of them, you can craft a Suspicious Looking Eye to summon the Eye of Cthulhu!",
  "Defeating the Eye of Cthulhu will grant you rare resources. Prepare a battle arena with Wood Platforms and Campfires first!",
  "Watch out for Shadow Orbs in the purple Corruption biomes. Breaking them can trigger cataclysmic events... or summon boss fights!"
];
