const SpiralRules={
 create(names,cards,random=Math.random){const deck=cards.map(c=>c.id);for(let i=deck.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[deck[i],deck[j]]=[deck[j],deck[i]];}const score=id=>cards.find(c=>c.id===id).score;const players=names.map(name=>({name,lane:deck.splice(0,3).sort((a,b)=>score(a)-score(b))}));return{version:3,players,deck,current:deck.pop(),starter:0,active:0,attempts:0,phase:'guess',result:null,discarded:[],winners:[]};},
 guess(game,slot,cards){if(game.phase!=='guess')return false;const lane=game.players[game.active].lane;if(!Number.isInteger(slot)||slot<0||slot>lane.length)return false;const score=id=>cards.find(c=>c.id===id).score,value=score(game.current);const correct=(slot===0||score(lane[slot-1])<value)&&(slot===lane.length||value<score(lane[slot]));const guesser=game.active;if(correct){lane.splice(slot,0,game.current);game.result={kind:'correct',player:guesser};if(lane.length>=10)game.winners=[guesser];}else{game.attempts++;game.result={kind:game.players.length===1||game.attempts===game.players.length?'discard':'pass',player:guesser};if(game.result.kind==='discard')game.discarded.push(game.current);}game.phase='result';return correct;},
 next(game){if(game.phase!=='result')return;if(game.result.kind==='pass'){game.active=(game.active+1)%game.players.length;game.phase='guess';game.result=null;return;}if(game.winners.length||!game.deck.length){if(!game.winners.length&&game.players.length>1){const high=Math.max(...game.players.map(p=>p.lane.length));game.winners=game.players.flatMap((p,i)=>p.lane.length===high?[i]:[]);}game.phase='end';return;}game.starter=(game.starter+1)%game.players.length;game.active=game.starter;game.attempts=0;game.current=game.deck.pop();game.phase='guess';game.result=null;}
};
if(typeof module!=='undefined')module.exports=SpiralRules;
if(typeof document!=='undefined'){
 const $=id=>document.getElementById(id),cards=new Map(DISASTER_CARDS.map(c=>[c.id,c])),prefsKey='rod-shit-spiral-players-v2';let count=1,names=Array.from({length:8},(_,i)=>i?'Player '+(i+1):'You'),game=null,selected=null;
 try{const p=JSON.parse(localStorage.getItem(prefsKey));if(Number.isInteger(p?.count)&&p.count>=1&&p.count<=8)count=p.count;if(Array.isArray(p?.names))p.names.slice(0,8).forEach((n,i)=>{if(typeof n==='string'&&n.trim())names[i]=n.slice(0,24);});}catch{}
 function savePrefs(){try{localStorage.setItem(prefsKey,JSON.stringify({count,names}));}catch{$('notice').textContent='Names could not be saved in this browser.';}}
 function buildNames(){$('names').replaceChildren();$('player-count').textContent=count;$('less').disabled=count===1;$('more').disabled=count===8;for(let i=0;i<count;i++){const label=document.createElement('label'),input=document.createElement('input');label.textContent=count===1?'NAME':'PLAYER '+(i+1);input.value=names[i];input.maxLength=24;input.autocomplete='off';input.oninput=()=>{names[i]=input.value;savePrefs();};label.append(input);$('names').append(label);}}
 function openRules(){$('rules').showModal();buildNames();}
 $('help').onclick=openRules;$('open-rules').onclick=openRules;$('close-rules').onclick=()=>{$('rules').close();savePrefs();};$('less').onclick=()=>{count=Math.max(1,count-1);savePrefs();buildNames();};$('more').onclick=()=>{count=Math.min(8,count+1);savePrefs();buildNames();};
 function start(){savePrefs();game=SpiralRules.create(names.slice(0,count).map((n,i)=>n.trim()||(count===1?'You':'Player '+(i+1))),DISASTER_CARDS);selected=null;$('rules').close();render();}
 $('play').onclick=start;$('play-settings').onclick=start;$('again').onclick=start;$('next').onclick=()=>{SpiralRules.next(game);selected=null;render();};
 $('home').onclick=()=>{if(game&&game.phase!=='end')$('confirm-home').showModal();else showHome();};$('stay').onclick=()=>$('confirm-home').close();$('leave').onclick=()=>{$('confirm-home').close();showHome();};
 function showHome(){game=null;selected=null;$('home').hidden=true;$('home-screen').hidden=false;$('play-screen').hidden=true;$('end-screen').hidden=true;}
 function choose(index){if(game.phase!=='guess')return;const lane=game.players[game.active].lane;if(selected===null){selected=index;renderLane();return;}let slot=null;if(selected===index&&(index===0||index===lane.length-1))slot=index===0?0:lane.length;else if(Math.abs(selected-index)===1)slot=Math.max(selected,index);if(slot===null){selected=index;renderLane();return;}selected=null;SpiralRules.guess(game,slot,DISASTER_CARDS);render();}
 function renderLane(){const player=game.players[game.active],result=game.phase==='result';$('lane').replaceChildren();player.lane.forEach((id,i)=>{const card=cards.get(id),button=document.createElement(result?'article':'button'),copy=document.createElement('div'),score=document.createElement('div');button.className='owned'+(result?'':' selectable')+(selected===i?' selected':'')+(selected!==null&&Math.abs(selected-i)===1?' between':'');copy.className='card-copy';copy.textContent=card.text;score.className='card-score';score.textContent=card.score;button.append(copy,score);if(!result){button.setAttribute('aria-label',(selected===null?'Select ':'Pair with ')+card.score);button.onclick=()=>choose(i);}$('lane').append(button);});}
 function render(){const ended=game.phase==='end';$('home').hidden=false;$('home-screen').hidden=true;$('play-screen').hidden=ended;$('end-screen').hidden=!ended;if(ended){const solo=game.players.length===1;$('winner').textContent=solo?(game.winners.length?'You survived.':'Out of cards.'):(game.winners.map(i=>game.players[i].name).join(' & ')+(game.winners.length===1?' wins.':' tie.'));$('end-message').textContent=solo?game.players[0].lane.length+'/10 cards collected.':game.players.map(p=>p.name+': '+p.lane.length).join(' · ');return;}
  const player=game.players[game.active],card=cards.get(game.current),result=game.phase==='result'?game.result:null;$('scoreboard').replaceChildren();game.players.forEach((p,i)=>{const chip=document.createElement('div');chip.className='player-chip'+(i===game.active?' current':'');chip.textContent=p.name;const n=document.createElement('strong');n.textContent=p.lane.length+'/10';chip.append(n);$('scoreboard').append(chip);});$('deck-count').textContent=game.players.length===1?'':'Deck '+game.deck.length;$('situation-text').textContent=card.text;const reveal=result&&result.kind!=='pass';$('rating').textContent=reveal?card.score:'?';$('rating').classList.toggle('hidden-number',!reveal);$('result').hidden=!result;
  if(result){const next=game.players[(game.active+1)%game.players.length].name;$('result-title').textContent=result.kind==='correct'?'Correct':'Wrong';$('result-text').textContent=result.kind==='correct'?player.lane.length+'/10 cards':result.kind==='pass'?'Pass to '+next+'. The score stays hidden.':game.players.length===1?'Try the next card.':String(card.score);$('next').textContent=game.winners.length?'Finish':result.kind==='pass'?'Pass to '+next:'Next card';}renderLane();
 }
 $('play-screen').addEventListener('click',event=>{if(selected===null||event.target.closest('.owned'))return;selected=null;renderLane();});
 buildNames();showHome();
}
