const SpiralLan={
 base64(bytes){let binary='';bytes.forEach(byte=>binary+=String.fromCharCode(byte));return btoa(binary).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');},
 bytes(value){let code=value.replaceAll('-','+').replaceAll('_','/');while(code.length%4)code+='=';return Uint8Array.from(atob(code),char=>char.charCodeAt(0));},
 async encode(value){const raw=new TextEncoder().encode(JSON.stringify(value));if(typeof CompressionStream==='undefined')return this.base64(raw);const stream=new Blob([raw]).stream().pipeThrough(new CompressionStream('deflate-raw'));return'S1.'+this.base64(new Uint8Array(await new Response(stream).arrayBuffer()));},
 async decode(value){const code=value.trim();if(!code.startsWith('S1.'))return JSON.parse(new TextDecoder().decode(this.bytes(code)));if(typeof DecompressionStream==='undefined')throw Error('Compressed invites are unsupported');const stream=new Blob([this.bytes(code.slice(3))]).stream().pipeThrough(new DecompressionStream('deflate-raw'));return JSON.parse(await new Response(stream).text());},
 async gathered(peer){if(peer.iceGatheringState==='complete')return;await new Promise(resolve=>{const done=()=>{if(peer.iceGatheringState==='complete'){peer.removeEventListener('icegatheringstatechange',done);resolve();}};peer.addEventListener('icegatheringstatechange',done);setTimeout(resolve,5000);});},
 peer(){return new RTCPeerConnection({iceServers:[]});},
 async host(){const peer=this.peer(),channel=peer.createDataChannel('shit-spiral');await peer.setLocalDescription(await peer.createOffer());await this.gathered(peer);return{peer,channel,offer:await this.encode(peer.localDescription),async accept(code){await peer.setRemoteDescription(await SpiralLan.decode(code));}};},
 async join(code){const peer=this.peer();let channel;const ready=new Promise(resolve=>peer.addEventListener('datachannel',event=>{channel=event.channel;resolve(channel);},{once:true}));await peer.setRemoteDescription(await this.decode(code));await peer.setLocalDescription(await peer.createAnswer());await this.gathered(peer);return{peer,ready,answer:await this.encode(peer.localDescription),get channel(){return channel;}};}
};
if(typeof module!=='undefined')module.exports=SpiralLan;
