const SpiralRules={
 create(names,cards,random=Math.random){const deck=cards.map(c=>c.id);for(let i=deck.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[deck[i],deck[j]]=[deck[j],deck[i]];}const score=id=>cards.find(c=>c.id===id).score;const players=names.map(name=>({name,lane:deck.splice(0,3).sort((a,b)=>score(a)-score(b))}));return{version:3,players,deck,current:deck.pop(),starter:0,active:0,attempts:0,phase:'guess',result:null,discarded:[],winners:[]};},
 guess(game,slot,cards){if(game.phase!=='guess')return false;const lane=game.players[game.active].lane;if(!Number.isInteger(slot)||slot<0||slot>lane.length)return false;const score=id=>cards.find(c=>c.id===id).score,value=score(game.current);const correct=(slot===0||score(lane[slot-1])<value)&&(slot===lane.length||value<score(lane[slot]));const guesser=game.active;if(correct){lane.splice(slot,0,game.current);game.result={kind:'correct',player:guesser};if(lane.length>=10)game.winners=[guesser];}else{game.attempts++;game.result={kind:game.players.length===1||game.attempts===game.players.length?'discard':'pass',player:guesser};if(game.result.kind==='discard')game.discarded.push(game.current);}game.phase='result';return correct;},
 next(game){if(game.phase!=='result')return;if(game.result.kind==='pass'){game.active=(game.active+1)%game.players.length;game.phase='guess';game.result=null;return;}if(game.winners.length||!game.deck.length){if(!game.winners.length&&game.players.length>1){const high=Math.max(...game.players.map(p=>p.lane.length));game.winners=game.players.flatMap((p,i)=>p.lane.length===high?[i]:[]);}game.phase='end';return;}game.starter=(game.starter+1)%game.players.length;game.active=game.starter;game.attempts=0;game.current=game.deck.pop();game.phase='guess';game.result=null;}
};
if(typeof module!=='undefined')module.exports=SpiralRules;
if(typeof document!=='undefined'){
 const $=id=>document.getElementById(id),cards=new Map(DISASTER_CARDS.map(c=>[c.id,c])),prefsKey='rod-shit-spiral-players-v2',touchCards=matchMedia('(hover: none)').matches;let count=1,names=Array.from({length:8},(_,i)=>i?'Player '+(i+1):'You'),game=null,selected=null,peeked=null,lan=null,localPlayer=null;
 try{const p=JSON.parse(localStorage.getItem(prefsKey));if(Number.isInteger(p?.count)&&p.count>=1&&p.count<=8)count=p.count;if(Array.isArray(p?.names))p.names.slice(0,8).forEach((n,i)=>{if(typeof n==='string'&&n.trim())names[i]=n.slice(0,24);});}catch{}
 function savePrefs(){try{localStorage.setItem(prefsKey,JSON.stringify({count,names}));}catch{$('notice').textContent='Names could not be saved in this browser.';}}
 function buildNames(){$('names').replaceChildren();$('player-count').textContent=count;$('less').disabled=count===1;$('more').disabled=count===8;for(let i=0;i<count;i++){const label=document.createElement('label'),input=document.createElement('input');label.textContent=count===1?'NAME':'PLAYER '+(i+1);input.value=names[i];input.maxLength=24;input.autocomplete='off';input.oninput=()=>{names[i]=input.value;savePrefs();};label.append(input);$('names').append(label);}}
 function openRules(){$('rules').showModal();buildNames();}
 $('help').onclick=openRules;$('open-rules').onclick=openRules;$('close-rules').onclick=()=>{$('rules').close();savePrefs();};$('less').onclick=()=>{count=Math.max(1,count-1);savePrefs();buildNames();};$('more').onclick=()=>{count=Math.min(8,count+1);savePrefs();buildNames();};
 function closeLan(){if(lan?.peer)lan.peer.close();lan=null;localPlayer=null;}
 function start(){closeLan();savePrefs();game=SpiralRules.create(names.slice(0,count).map((n,i)=>n.trim()||(count===1?'You':'Player '+(i+1))),DISASTER_CARDS);selected=null;peeked=null;$('rules').close();render();}
 function send(message){if(lan?.channel?.readyState==='open')lan.channel.send(JSON.stringify(message));}
 function publish(){if(lan?.host)send({type:'state',game});}
 function applyAction(action){if(!game||game.active!==action.player)return;if(action.kind==='guess'&&game.phase==='guess')SpiralRules.guess(game,action.slot,DISASTER_CARDS);else if(action.kind==='next'&&game.phase==='result'&&game.result.player===action.player)SpiralRules.next(game);else return;selected=null;peeked=null;render();publish();}
 function networkAction(action){action.player=localPlayer;if(lan.host)applyAction(action);else send({type:'action',action});}
 function attachChannel(channel,isHost){lan.channel=channel;channel.onopen=()=>{setLanStatus('Connected. Starting game…');if(!isHost)send({type:'hello',name:lan.name});};channel.onclose=()=>{$('notice').textContent='LAN player disconnected.';};channel.onerror=()=>setLanStatus('Connection failed. Create fresh pairing codes and try again.');channel.onmessage=event=>{const message=JSON.parse(event.data);if(isHost&&message.type==='hello'){game=SpiralRules.create([lan.name,message.name||'Player 2'],DISASTER_CARDS);localPlayer=0;$('lan-dialog').close();render();publish();}else if(isHost&&message.type==='action')applyAction(message.action);else if(!isHost&&message.type==='state'){game=message.game;localPlayer=1;$('lan-dialog').close();selected=null;render();}};}
 function setLanStatus(text){$('lan-status').textContent=text;}
 $('lan-play').onclick=()=>{$('lan-dialog').showModal();setLanStatus('');};$('close-lan').onclick=()=>{$('lan-dialog').close();closeLan();};
 $('make-offer').onclick=async()=>{try{closeLan();setLanStatus('Creating invite…');lan=await SpiralLan.host();lan.host=true;lan.name=$('lan-name').value.trim()||'Host';attachChannel(lan.channel,true);$('offer-out').value=lan.offer;setLanStatus('Send the invite code to player 2.');}catch{setLanStatus('Could not create the LAN invite in this browser.');}};
 $('accept-answer').onclick=async()=>{try{if(!lan?.host)throw Error();await lan.accept($('answer-in').value);setLanStatus('Connecting…');}catch{setLanStatus('That join code is invalid.');}};
 $('make-answer').onclick=async()=>{try{closeLan();setLanStatus('Creating join code…');lan=await SpiralLan.join($('offer-in').value);lan.host=false;lan.name=$('lan-name').value.trim()||'Player 2';$('answer-out').value=lan.answer;lan.ready.then(channel=>attachChannel(channel,false));setLanStatus('Send the join code back to the host.');}catch{setLanStatus('That invite code is invalid or unsupported.');}};
 async function copy(id,label){try{await navigator.clipboard.writeText($(id).value);setLanStatus(label+' copied.');}catch{setLanStatus('Select the code and copy it manually.');}}
 $('copy-offer').onclick=()=>copy('offer-out','Invite');$('copy-answer').onclick=()=>copy('answer-out','Join code');
 $('play').onclick=start;$('play-settings').onclick=start;$('again').onclick=()=>lan?location.reload():start();$('next').onclick=()=>{if(lan)networkAction({kind:'next'});else{SpiralRules.next(game);selected=null;peeked=null;render();}};
 $('home').onclick=()=>{if(game&&game.phase!=='end')$('confirm-home').showModal();else showHome();};$('stay').onclick=()=>$('confirm-home').close();$('leave').onclick=()=>{$('confirm-home').close();showHome();};
 function showHome(){closeLan();game=null;selected=null;peeked=null;document.body.classList.remove('game-active');$('home').hidden=true;$('home-screen').hidden=false;$('play-screen').hidden=true;$('end-screen').hidden=true;}
 function choose(index){if(game.phase!=='guess'||(lan&&game.active!==localPlayer))return;const lane=game.players[game.active].lane;if(touchCards&&selected===null&&peeked!==index){peeked=index;renderLane();return;}if(selected===null){selected=index;peeked=null;renderLane();return;}let slot=null;if(selected===index&&(index===0||index===lane.length-1))slot=index===0?0:lane.length;else if(Math.abs(selected-index)===1)slot=Math.max(selected,index);if(slot===null){selected=index;peeked=null;renderLane();return;}selected=null;peeked=null;if(lan)networkAction({kind:'guess',slot});else{SpiralRules.guess(game,slot,DISASTER_CARDS);render();}}
 function renderLane(){const laneElement=$('lane'),scroll=laneElement.scrollLeft,owner=lan?localPlayer:game.active,player=game.players[owner],result=game.phase==='result',canChoose=!result&&(!lan||game.active===localPlayer);laneElement.replaceChildren();player.lane.forEach((id,i)=>{const card=cards.get(id),button=document.createElement(canChoose?'button':'article'),copy=document.createElement('div'),score=document.createElement('div');button.className='owned'+(canChoose?' selectable':'')+(peeked===i?' peeked':'')+(selected===i?' selected':'')+(selected!==null&&Math.abs(selected-i)===1?' between':'');copy.className='card-copy';copy.textContent=card.text;score.className='card-score';score.textContent=card.score;button.append(copy,score);if(canChoose){button.setAttribute('aria-label',(peeked===i?'Select ':selected===null?'Preview ':'Pair with ')+card.score);button.onclick=()=>choose(i);}laneElement.append(button);});laneElement.scrollLeft=scroll;}
 function render(){const ended=game.phase==='end';document.body.classList.toggle('game-active',!ended);$('home').hidden=false;$('home-screen').hidden=true;$('play-screen').hidden=ended;$('end-screen').hidden=!ended;if(ended){const solo=game.players.length===1;$('winner').textContent=solo?(game.winners.length?'You survived.':'Out of cards.'):(game.winners.map(i=>game.players[i].name).join(' & ')+(game.winners.length===1?' wins.':' tie.'));$('end-message').textContent=solo?game.players[0].lane.length+'/10 cards collected.':game.players.map(p=>p.name+': '+p.lane.length).join(' · ');return;}
  const player=game.players[game.active],card=cards.get(game.current),result=game.phase==='result'?game.result:null;$('scoreboard').replaceChildren();game.players.forEach((p,i)=>{const chip=document.createElement('div');chip.className='player-chip'+(i===game.active?' current':'');chip.textContent=p.name;const n=document.createElement('strong');n.textContent=p.lane.length+'/10';chip.append(n);$('scoreboard').append(chip);});$('deck-count').textContent=game.players.length===1?'':lan?(game.active===localPlayer?'Your turn':'Waiting for '+player.name):'Deck '+game.deck.length;$('situation-text').textContent=card.text;const reveal=result&&result.kind!=='pass';$('rating').textContent=reveal?card.score:'?';$('rating').classList.toggle('hidden-number',!reveal);$('result').hidden=!result;
  if(result){const next=game.players[(game.active+1)%game.players.length].name;$('result-title').textContent=result.kind==='correct'?'Correct':'Wrong';$('result-text').textContent=result.kind==='correct'?player.lane.length+'/10 cards':result.kind==='pass'?'Pass to '+next+'. The score stays hidden.':game.players.length===1?'Try the next card.':String(card.score);$('next').textContent=game.winners.length?'Finish':result.kind==='pass'?'Pass to '+next:'Next card';$('next').disabled=!!lan&&result.player!==localPlayer;}renderLane();
 }
 $('play-screen').addEventListener('click',event=>{if((selected===null&&peeked===null)||event.target.closest('.owned'))return;selected=null;peeked=null;renderLane();});
 buildNames();showHome();
}
