// Original situations with a custom subjective Misery Index.
const DISASTER_CARDS = [
  {"id": 0, "score": 0.5, "text": "Having to wait 30 seconds for a webpage to load"},
  {"id": 1, "score": 1.0, "text": "Your socks get slightly damp from morning dew"},
  {"id": 2, "score": 1.5, "text": "Someone leaves the toilet seat up"},
  {"id": 3, "score": 2.0, "text": "You drop a single french fry on the floor"},
  {"id": 4, "score": 2.5, "text": "Your sleeve catches on a door handle as you walk past"},
  {"id": 5, "score": 3.0, "text": "Having to go to court as a spectator when you really didn’t want to"},
  {"id": 6, "score": 3.5, "text": "Your headphones get tangled into an impossible knot"},
  {"id": 7, "score": 4.0, "text": "Your phone dies at 2% with no charger nearby"},
  {"id": 8, "score": 4.5, "text": "Stepping in a puddle with socks on"},
  {"id": 9, "score": 5.0, "text": "Getting a paper cut between your fingers"},
  {"id": 10, "score": 5.5, "text": "Someone microwaves fish in the office"},
  {"id": 11, "score": 6.0, "text": "Stepping on a bee with bare feet"},
  {"id": 12, "score": 6.5, "text": "Getting a hangnail that rips halfway down"},
  {"id": 13, "score": 7.0, "text": "Walking into a spiderweb face-first at night"},
  {"id": 14, "score": 7.5, "text": "Realizing you’ve been walking around with your fly open all morning"},
  {"id": 15, "score": 8.0, "text": "Walking into a glass door in front of people"},
  {"id": 16, "score": 8.5, "text": "Getting a parking ticket for being three minutes over"},
  {"id": 17, "score": 9.0, "text": "Your favorite mug breaks the day after you bought it"},
  {"id": 18, "score": 9.5, "text": "Someone takes the last parking spot you were waiting for"},
  {"id": 19, "score": 10.0, "text": "Getting stuck behind a person counting exact change"},
  {"id": 20, "score": 10.5, "text": "Losing a $20 bill to a vending machine that doesn’t give change"},
  {"id": 21, "score": 11.0, "text": "Spilling coffee on your only clean work shirt right before leaving"},
  {"id": 22, "score": 11.5, "text": "Someone steals your lunch from the office fridge"},
  {"id": 23, "score": 12.0, "text": "Your Amazon package is marked delivered but is nowhere to be found"},
  {"id": 24, "score": 12.5, "text": "Getting locked out of your apartment in the rain"},
  {"id": 25, "score": 13.0, "text": "Accidentally liking a 4-year-old photo while stalking your ex"},
  {"id": 26, "score": 13.5, "text": "Sneezing so hard you throw out your back"},
  {"id": 27, "score": 14.0, "text": "Getting food poisoning from the place you paid $40 for"},
  {"id": 28, "score": 14.5, "text": "Your dog throws up on your only clean sheets the night before guests"},
  {"id": 29, "score": 15.0, "text": "Your car gets a flat on the way to an important interview"},
  {"id": 30, "score": 15.5, "text": "Missing your flight because security took 90 minutes"},
  {"id": 31, "score": 16.0, "text": "Accidentally reply-all to a company-wide email with a private complaint"},
  {"id": 32, "score": 16.5, "text": "Getting a cavity filled and the drill hits a nerve"},
  {"id": 33, "score": 17.0, "text": "Your laptop dies the night a major project is due and you have no backup"},
  {"id": 34, "score": 17.5, "text": "Getting stuck in an elevator with someone who just farted"},
  {"id": 35, "score": 18.0, "text": "Your phone falls in the toilet mid-shit and you have to fish it out"},
  {"id": 36, "score": 18.5, "text": "Waking up and realizing you slept through your alarm for an important exam"},
  {"id": 37, "score": 19.0, "text": "Your credit card gets declined at a fancy restaurant in front of a date"},
  {"id": 38, "score": 19.5, "text": "Getting food poisoning so bad you have to cancel plans"},
  {"id": 39, "score": 20.0, "text": "Accidentally sending a thirsty text to your mom"},
  {"id": 40, "score": 20.5, "text": "Walking in on your roommate having sex and they don’t stop"},
  {"id": 41, "score": 21.0, "text": "Getting food poisoning on the first day of a week-long vacation"},
  {"id": 42, "score": 21.5, "text": "Getting a cavity and needing a root canal the same day"},
  {"id": 43, "score": 22.0, "text": "Your flight gets delayed 6 hours and then cancelled"},
  {"id": 44, "score": 22.5, "text": "Getting a positive COVID test the day before a long-planned trip"},
  {"id": 45, "score": 23.0, "text": "Dropping your phone face-down on concrete and cracking the screen"},
  {"id": 46, "score": 23.5, "text": "Getting a parking boot the day you have a final exam"},
  {"id": 47, "score": 24.0, "text": "Getting food poisoning so bad you shit yourself in public"},
  {"id": 48, "score": 24.5, "text": "Discovering your partner has been using your Netflix with someone else"},
  {"id": 49, "score": 25.0, "text": "Your boss publicly takes credit for your idea in a big meeting"},
  {"id": 50, "score": 25.5, "text": "Finding out your best friend has been talking shit about you for years"},
  {"id": 51, "score": 26.0, "text": "Accidentally sending a dick pic to the family group chat"},
  {"id": 52, "score": 26.5, "text": "Discovering you have an identical twin who has been living your life better"},
  {"id": 53, "score": 27.0, "text": "Discovering your partner has a secret second phone"},
  {"id": 54, "score": 27.5, "text": "Your landlord sells the building and gives you 30 days with no deposit back"},
  {"id": 55, "score": 28.0, "text": "Getting laid off the same week your rent increases"},
  {"id": 56, "score": 28.5, "text": "Your house has black mold and the landlord refuses to fix it"},
  {"id": 57, "score": 29.0, "text": "Getting a call that your pet has been hit by a car"},
  {"id": 58, "score": 29.5, "text": "Getting doxxed and your home address is posted online"},
  {"id": 59, "score": 30.0, "text": "Your car gets totaled and insurance lowballs you by $8k"},
  {"id": 60, "score": 30.5, "text": "Getting scammed out of a large chunk of savings by a ‘friend’"},
  {"id": 61, "score": 31.0, "text": "Getting a positive pregnancy test from a one-night stand and the other person blocks you"},
  {"id": 62, "score": 31.5, "text": "Getting publicly canceled for something you said in a private group chat 8 years ago"},
  {"id": 63, "score": 32.0, "text": "Discovering your partner has been recording your arguments and sending them to friends"},
  {"id": 64, "score": 32.5, "text": "Getting a call that your parent is in the hospital and you’re the only one who can go"},
  {"id": 65, "score": 33.0, "text": "Walking in on your partner mid-act with your boss"},
  {"id": 66, "score": 33.5, "text": "Finding out every achievement in your life was given to you as a joke"},
  {"id": 67, "score": 34.0, "text": "Getting a positive test for a permanent STI from your long-term partner"},
  {"id": 68, "score": 34.5, "text": "Getting blackmailed with nudes you sent years ago"},
  {"id": 69, "score": 35.0, "text": "Discovering your partner has been in love with your best friend the entire relationship"},
  {"id": 70, "score": 35.5, "text": "Finding out your partner has been cheating for over a year"},
  {"id": 71, "score": 36.0, "text": "Finding out your ‘therapist’ has been recording sessions and selling them"},
  {"id": 72, "score": 36.5, "text": "Your house burns down and insurance finds a reason not to pay"},
  {"id": 73, "score": 37.0, "text": "Getting diagnosed with a chronic illness that will never fully go away"},
  {"id": 74, "score": 37.5, "text": "Finding out the person you married is already married to someone else"},
  {"id": 75, "score": 38.0, "text": "Losing your job and your partner leaving you in the same month"},
  {"id": 76, "score": 38.5, "text": "Accidentally running over your own pet"},
  {"id": 77, "score": 39.0, "text": "Discovering your partner has been selling your nudes without consent"},
  {"id": 78, "score": 39.5, "text": "Getting diagnosed with a genetic condition that will eventually kill you"},
  {"id": 79, "score": 40.0, "text": "Walking in on your partner having sex with your sibling"},
  {"id": 80, "score": 40.5, "text": "Finding out your partner has been filming you without consent for years"},
  {"id": 81, "score": 41.0, "text": "Finding out your partner has been in a secret relationship for years"},
  {"id": 82, "score": 41.5, "text": "Finding out your best friend has been sleeping with your partner for months"},
  {"id": 83, "score": 42.0, "text": "Discovering your entire extended family has been watching your private content"},
  {"id": 84, "score": 42.5, "text": "Finding out your partner has been cheating with your therapist"},
  {"id": 85, "score": 43.0, "text": "Getting a call that your parent died and the other parent is too busy to come to the funeral"},
  {"id": 86, "score": 43.5, "text": "Discovering you were switched at birth and your real family wants nothing to do with you"},
  {"id": 87, "score": 44.0, "text": "Walking in on your partner mid-act with your best friend"},
  {"id": 88, "score": 44.5, "text": "Your entire life savings gets wiped out by a market crash the day after you invest"},
  {"id": 89, "score": 45.0, "text": "Finding out every person you love has been lying to you your entire life"},
  {"id": 90, "score": 45.5, "text": "Getting permanently banned from your country with no way to appeal"},
  {"id": 91, "score": 46.0, "text": "Finding out you have been in a simulation and none of your memories are real"},
  {"id": 92, "score": 46.5, "text": "Watching your house burn down with everything you own inside"},
  {"id": 93, "score": 47.0, "text": "Finding out you have been brainwashed your entire life and your identity is fake"},
  {"id": 94, "score": 47.5, "text": "Getting diagnosed with a rare disease that has no cure"},
  {"id": 95, "score": 48.0, "text": "Finding out your entire family has been in a cult that plans to sacrifice you"},
  {"id": 96, "score": 48.5, "text": "Finding out your entire bloodline is cursed and every relative dies young in agony"},
  {"id": 97, "score": 49.0, "text": "Getting infected with a highly contagious disease that forces you into permanent isolation"},
  {"id": 98, "score": 49.5, "text": "Getting diagnosed with stage 3 cancer at 32"},
  {"id": 99, "score": 50.0, "text": "Getting sentenced to 10 years in prison for a crime you didn’t commit"},
  {"id": 100, "score": 50.5, "text": "Getting kidnapped and held for ransom that no one can pay"},
  {"id": 101, "score": 51.0, "text": "Getting trapped in a time loop where you relive the worst day of your life forever"},
  {"id": 102, "score": 51.5, "text": "Finding out you are the reason an entire generation of people suffered"},
  {"id": 103, "score": 52.0, "text": "Being the only person who remembers a loved one who was erased from existence"},
  {"id": 104, "score": 52.5, "text": "Watching the world end in real time while knowing you caused it"},
  {"id": 105, "score": 53.0, "text": "Getting your consciousness trapped in a dying body with full awareness"},
  {"id": 106, "score": 53.5, "text": "Finding out you have been dead for years and this is just a fading memory"},
  {"id": 107, "score": 54.0, "text": "Being forced to live forever with the knowledge of every mistake you ever made"},
  {"id": 108, "score": 54.5, "text": "Getting trapped in a collapsed building for days with no rescue coming"},
  {"id": 109, "score": 55.0, "text": "Watching every person you ever loved die of old age while you stay young"},
  {"id": 110, "score": 55.5, "text": "Getting your soul sold without your knowledge and spending eternity in torment"},
  {"id": 111, "score": 56.0, "text": "Finding out reality itself is collapsing and you are the only one who knows"},
  {"id": 112, "score": 56.5, "text": "Being the last conscious being in a universe that is heat-deathing around you"},
  {"id": 113, "score": 57.0, "text": "Watching your own mind slowly dissolve into irreversible dementia"},
  {"id": 114, "score": 57.5, "text": "Getting every memory of happiness erased while keeping all the pain"},
  {"id": 115, "score": 58.0, "text": "Finding out you will never see another human face again for the rest of eternity"},
  {"id": 116, "score": 58.5, "text": "Getting a call that both your parents died in a car crash"},
  {"id": 117, "score": 59.0, "text": "Finding out you accidentally killed someone and framed an innocent person"},
  {"id": 118, "score": 59.5, "text": "Being forced to experience every death that has ever happened in human history"},
  {"id": 119, "score": 60.0, "text": "Watching the heat death of the universe from inside a failing spaceship"},
  {"id": 120, "score": 60.5, "text": "Getting your identity completely overwritten so the original you no longer exists"},
  {"id": 121, "score": 61.0, "text": "Finding out love, meaning, and consciousness were all illusions"},
  {"id": 122, "score": 61.5, "text": "Being the only entity left after the end of time with nothing left to experience"},
  {"id": 123, "score": 62.0, "text": "Watching every possible version of yourself fail and die across infinite timelines"},
  {"id": 124, "score": 62.5, "text": "Getting trapped in a perfect simulation of your worst fear that never ends"},
  {"id": 125, "score": 63.0, "text": "Finding out you are a secondary character in someone else’s story and your life never mattered"},
  {"id": 126, "score": 63.5, "text": "Being forced to relive the exact moment you lost everything on infinite loop"},
  {"id": 127, "score": 64.0, "text": "Watching the concept of hope itself get erased from the universe"},
  {"id": 128, "score": 64.5, "text": "Getting every positive emotion surgically removed from your brain permanently"},
  {"id": 129, "score": 65.0, "text": "Finding out the universe was created solely to make you suffer"},
  {"id": 130, "score": 65.5, "text": "Being the final thought of a dying god who regrets creating consciousness"},
  {"id": 131, "score": 66.0, "text": "Finding out your partner has been poisoning you slowly for months"},
  {"id": 132, "score": 66.5, "text": "Being forced to eat your own pet to survive"},
  {"id": 133, "score": 67.0, "text": "Watching existence itself apologize for ever allowing you to be born"},
  {"id": 134, "score": 67.5, "text": "Getting your entire life retroactively erased so you never existed"},
  {"id": 135, "score": 68.0, "text": "Finding out there is no afterlife, no meaning, and no one will ever remember you"},
  {"id": 136, "score": 68.5, "text": "Being the last spark of awareness before total and permanent nothingness"},
  {"id": 137, "score": 69.0, "text": "Watching the final star burn out while knowing nothing comes after"},
  {"id": 138, "score": 69.5, "text": "Getting the knowledge that everything you ever did made the universe worse"},
  {"id": 139, "score": 70.0, "text": "Finding out you will experience infinite suffering with full consciousness forever"},
  {"id": 140, "score": 70.5, "text": "Getting permanently paralyzed from the neck down after a preventable accident"},
  {"id": 141, "score": 71.0, "text": "Being forced to watch every person you love experience the same fate as you"},
  {"id": 142, "score": 71.5, "text": "Watching the last remnant of human culture get destroyed with no record left"},
  {"id": 143, "score": 72.0, "text": "Getting the certainty that free will never existed and every choice was predetermined pain"},
  {"id": 144, "score": 72.5, "text": "Finding out the true nature of reality is pure malevolence directed at you"},
  {"id": 145, "score": 73.0, "text": "Being the only thing that exists and realizing you are the source of all suffering"},
  {"id": 146, "score": 73.5, "text": "Watching time itself end while your consciousness continues in total isolation"},
  {"id": 147, "score": 74.0, "text": "Getting the final revelation that every moment of joy was a lie designed to hurt more later"},
  {"id": 148, "score": 74.5, "text": "Finding out there is no escape, no death, and no end to the torment"},
  {"id": 149, "score": 75.0, "text": "Being forced to exist as pure awareness of infinite loss with no body left to die"},
  {"id": 150, "score": 75.5, "text": "Watching the last possible version of a happy ending get deleted from possibility"},
  {"id": 151, "score": 76.0, "text": "Getting the knowledge that you are the reason the universe can never be good"},
  {"id": 152, "score": 76.5, "text": "Finding out even oblivion is denied to you and awareness continues forever"},
  {"id": 153, "score": 77.0, "text": "Being the final prisoner of a reality that has no exit and no mercy"},
  {"id": 154, "score": 77.5, "text": "Getting diagnosed with late-stage cancer and given 3 months to live"},
  {"id": 155, "score": 78.0, "text": "Being the subject of a lifelong medical experiment against your will"},
  {"id": 156, "score": 78.5, "text": "Watching every possible future collapse into the same eternal nightmare"},
  {"id": 157, "score": 79.0, "text": "Getting the certainty that this is the best possible timeline and it is still hell"},
  {"id": 158, "score": 79.5, "text": "Finding out the only thing that ever loved you was also the thing that destroyed you"},
  {"id": 159, "score": 80.0, "text": "Being forced to experience the death of meaning itself with full understanding"},
  {"id": 160, "score": 80.5, "text": "Existing forever as the sole witness to the total and permanent end of everything that ever mattered"},
  {"id": 161, "score": 81.0, "text": "Your partner dies in your arms after a preventable accident you caused"},
  {"id": 162, "score": 81.5, "text": "Your child gets diagnosed with a terminal illness"},
  {"id": 163, "score": 82.0, "text": "Getting buried alive with limited air and no one knowing where you are"},
  {"id": 164, "score": 82.5, "text": "Getting sentenced to life in solitary confinement with no possibility of parole"},
  {"id": 165, "score": 83.0, "text": "Watching your child get diagnosed with the same terminal illness that killed you"},
  {"id": 166, "score": 83.5, "text": "Being the only survivor of a plane crash that killed everyone you know"},
  {"id": 167, "score": 84.0, "text": "Being the last human left on Earth after a global extinction event"},
  {"id": 168, "score": 84.5, "text": "Being forced to live the rest of your life with full-body burns and constant pain"},
  {"id": 169, "score": 85.0, "text": "Being forced to choose which of your children lives in a medical crisis"},
  {"id": 170, "score": 85.5, "text": "Getting tortured for information you don’t have for weeks"},
  {"id": 171, "score": 86.0, "text": "Watching your entire city get nuked while you survive in a bunker alone"},
  {"id": 172, "score": 86.5, "text": "Watching your partner get murdered while you are restrained and helpless"},
  {"id": 173, "score": 87.0, "text": "Watching your entire family get executed in front of you"},
  {"id": 174, "score": 87.5, "text": "Watching your child get taken by human traffickers with no way to stop it"},
  {"id": 175, "score": 88.0, "text": "Being forced to kill your own family to save a larger group of people"},
  {"id": 176, "score": 88.5, "text": "Watching your parents get tortured to death while they beg you to help"},
  {"id": 177, "score": 89.0, "text": "Walking in on your parents mid-act and they just continue"},
  {"id": 178, "score": 89.5, "text": "Discovering your partner has been in love with your parent the whole time"},
  {"id": 179, "score": 90.0, "text": "Walking in on your partner and your parent mid-act"},
  {"id": 180, "score": 90.5, "text": "Walking in on your parents mid-act with your high school teacher"},
  {"id": 181, "score": 91.0, "text": "Finding out your parents have a secret OnlyFans and your childhood bedroom is the set"},
  {"id": 182, "score": 91.5, "text": "Walking in on your parents watching their own sex tapes while talking about you"},
  {"id": 183, "score": 92.0, "text": "Walking in on your parents watching porn WITH them and they don’t pause it"},
  {"id": 184, "score": 92.5, "text": "Discovering your entire family has been watching your private content together"},
  {"id": 185, "score": 93.0, "text": "Being the subject of a family sex tape that got leaked"},
  {"id": 186, "score": 93.5, "text": "Finding out your sibling has been in a relationship with your parent"},
  {"id": 187, "score": 94.0, "text": "Getting a positive pregnancy test and the only possible father is a family member"},
  {"id": 188, "score": 94.5, "text": "Getting blackmailed with a sex tape involving a family member"},
  {"id": 189, "score": 95.0, "text": "Discovering your parents have been recording and watching themselves having sex with your sibling"},
  {"id": 190, "score": 95.5, "text": "Getting forced to watch a video of your parents having sex as a ‘lesson’"},
  {"id": 191, "score": 96.0, "text": "Discovering your parents have been livestreaming their sex life with your name in the title"},
  {"id": 192, "score": 96.5, "text": "Finding out your parents have been having threesomes with your current partner"},
  {"id": 193, "score": 97.0, "text": "Finding out your parents have been selling videos of themselves having sex with your partner"},
  {"id": 194, "score": 97.5, "text": "Walking in on your parents mid-threesome and they ask you to join"},
  {"id": 195, "score": 98.0, "text": "Getting invited to (and expected to join) a threesome with your parents"},
  {"id": 196, "score": 98.5, "text": "Being forced to watch your parents have sex as ‘punishment’"},
  {"id": 197, "score": 99.0, "text": "Getting forced to film a threesome with your parents for their content"},
  {"id": 198, "score": 99.5, "text": "Discovering your parents used your identity to publish their entire sex life and everyone you know has seen it"},
  {"id": 199, "score": 100.0, "text": "Being forced to participate in a threesome with both of your parents"}
];
