/* Serverless WebRTC sessions for Rod Space. Each guest pairs directly with the host. */
const PartyLan=(()=>{
 const listeners=()=>{const map=new Map();return{on(type,fn){if(!map.has(type))map.set(type,new Set());map.get(type).add(fn);return()=>map.get(type)?.delete(fn)},emit(type,value){map.get(type)?.forEach(fn=>fn(value))}}};
 const b64=bytes=>{let s='';bytes.forEach(v=>s+=String.fromCharCode(v));return btoa(s).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')};
 const bytes=value=>{let s=value.replaceAll('-','+').replaceAll('_','/');while(s.length%4)s+='=';return Uint8Array.from(atob(s),c=>c.charCodeAt(0))};
 async function encode(value){const raw=new TextEncoder().encode(JSON.stringify(value));if(!globalThis.CompressionStream)return b64(raw);const stream=new Blob([raw]).stream().pipeThrough(new CompressionStream('deflate-raw'));return'P1.'+b64(new Uint8Array(await new Response(stream).arrayBuffer()))}
 async function decode(value){const code=value.trim();if(!code.startsWith('P1.'))return JSON.parse(new TextDecoder().decode(bytes(code)));if(!globalThis.DecompressionStream)throw Error('Compressed pairing codes are unsupported in this browser');const stream=new Blob([bytes(code.slice(3))]).stream().pipeThrough(new DecompressionStream('deflate-raw'));return JSON.parse(await new Response(stream).text())}
 async function gathered(peer){if(peer.iceGatheringState==='complete')return;await new Promise(resolve=>{const done=()=>{if(peer.iceGatheringState==='complete'){peer.removeEventListener('icegatheringstatechange',done);resolve()}};peer.addEventListener('icegatheringstatechange',done);setTimeout(resolve,5000)})}
 const peer=()=>new RTCPeerConnection({iceServers:[]});
 function wire(channel,events,info){channel.addEventListener('open',()=>events.emit('open',info));channel.addEventListener('close',()=>events.emit('close',info));channel.addEventListener('message',event=>{try{events.emit('message',{peer:info,data:JSON.parse(event.data)})}catch{}})}
 function send(channel,type,payload){if(channel?.readyState==='open')channel.send(JSON.stringify({type,payload}))}
 function host(){const events=listeners(),guests=[];return{guests,on:events.on,async invite(meta={}){const rtc=peer(),channel=rtc.createDataChannel('rod-party',{ordered:true}),guest={id:crypto.randomUUID(),meta,rtc,channel};guests.push(guest);wire(channel,events,guest);await rtc.setLocalDescription(await rtc.createOffer());await gathered(rtc);return{guest,code:await encode(rtc.localDescription),async accept(answer){await rtc.setRemoteDescription(await decode(answer));return guest}}},send(guest,type,payload){send(guest.channel,type,payload)},broadcast(type,payload){guests.forEach(g=>send(g.channel,type,payload))},close(){guests.forEach(g=>g.rtc.close())}}}
 async function join(code,meta={}){const events=listeners(),rtc=peer();let channel;const ready=new Promise(resolve=>rtc.addEventListener('datachannel',event=>{channel=event.channel;wire(channel,events,meta);resolve(channel)},{once:true}));await rtc.setRemoteDescription(await decode(code));await rtc.setLocalDescription(await rtc.createAnswer());await gathered(rtc);return{rtc,meta,on:events.on,ready,answer:await encode(rtc.localDescription),send(type,payload){send(channel,type,payload)},close(){rtc.close()}}}
 return{encode,decode,host,join};
})();
if(typeof module!=='undefined')module.exports=PartyLan;
