"use strict";
const SAVE_KEY="chronos_save_v3";
const eras=[
 {name:"The Pre-Void",kicker:"ERA I · PRIMORDIAL",desc:"Darkness moves upon the deep.",min:0,image:"assets/chronos/era-0-pre-void.png",alt:"A primordial black hole"},
 {name:"Hadean Inferno",kicker:"ERA II · IGNITION",desc:"Stone becomes fire beneath impossible gravity.",min:500,image:"assets/chronos/era-1-hadean-inferno.png",alt:"A molten world falling around a black hole"},
 {name:"Archean Waters",kicker:"ERA III · OCEANS",desc:"Rain outlives the fire and gathers into seas.",min:20000,image:"assets/chronos/era-2-archean-waters.png",alt:"An ocean world orbiting a dark core"},
 {name:"Verdant Bloom",kicker:"ERA IV · LIFE",desc:"The first green breath crosses the continents.",min:500000,image:"assets/chronos/era-3-verdant-bloom.png",alt:"A living green world around a cosmic core"},
 {name:"Techno-Organic",kicker:"ERA V · TRANSCENDENCE",desc:"Life and machine become one celestial mind.",min:25000000,image:"assets/chronos/era-4-techno-organic.png",alt:"A violet techno-organic world surrounding a black hole"}
];
const chapters=[
 {name:"The Big Bang",eras:["The Singularity","Cosmic Inflation","Particle Dawn","First Light","Galactic Web"],upgrades:["Expansion Pulse","Quantum Foam","Photon Storm","Matter Seed","Gravity Well","Star Nursery","Cosmic Loom","Dark Matter Halo","Fusion Epoch","Galaxy Crown","Quasar Beacon","Spacetime Root","Expansion Engine","Universe Seed"],seals:["Let There Be Space","Particle Sea","First Atom","First Star","The Galactic Web","Big Bang Complete"]},
 {name:"The Stellar Age",eras:["Molecular Cloud","Protostar","Main Sequence","Red Giant","Supernova Legacy"],upgrades:["Core Pressure","Dust Accretion","Hydrogen Flash","Fusion Heart","Magnetic Dynamo","Planetary Disc","Helium Forge","Carbon Crucible","Neutron Furnace","Solar Dominion","Pulsar Choir","Element Foundry","Supernova Engine","Stellar Legacy"],seals:["Cloud Collapse","A Star Is Born","Stable Flame","Heavy Elements","Death of a Star","Stellar Age Complete"]},
 {name:"The Living Cosmos",eras:["Barren Ocean","Chemical Dawn","First Cell","Complex Life","Cosmic Mind"],upgrades:["Chemical Spark","Warm Current","Lightning Cycle","Living Membrane","Tidal Rhythm","Oxygen Bloom","Genome Loom","Cambrian Engine","Nervous Constellation","Planetary Mind","Dreaming Biosphere","Evolution Root","Gaia Furnace","Conscious Cosmos"],seals:["Primordial Soup","Self Replication","Blue-Green Dawn","Many Forms","Awakened World","Living Cosmos Complete"]},
 {name:"The Machine Cosmos",eras:["Signal Dawn","Orbital Industry","Dyson Swarm","Galactic Network","Synthetic Universe"],upgrades:["Logic Spark","Mining Drone","Solar Relay","Machine Core","Orbital Forge","Dyson Choir","Quantum Processor","Nanite Cloud","Epoch Computer","Network Crown","Singularity Beacon","Reality Compiler","Eternity Server","Simulation Seed"],seals:["First Instruction","Autonomous Forge","Captured Sun","Connected Galaxy","Reality Computed","Machine Cosmos Complete"]},
 {name:"The Long Night",eras:["Fading Stars","Black Dwarfs","Evaporating Holes","Final Orbit","Heat Death"],upgrades:["Last Ember","Degenerate Matter","Hawking Spark","Frozen Core","Entropy Mill","Dying Choir","Vacuum Loom","Proton Clock","Black Dwarf Engine","Night Crown","Final Beacon","Entropy Root","Last Furnace","Rebirth Seed"],seals:["The Last Star","Cold Remnant","Black Hole Winter","One Final Orbit","Perfect Silence","Long Night Complete"]}
];
const upgrades=[
 {id:"focus",icon:"✦",name:"Divine Will",cost:15,type:"click",power:.4,desc:"Strengthens every manual harvest"},
 {id:"gravity",icon:"◉",name:"Primal Mass",cost:60,type:"auto",power:.8,desc:"Passively gathers Star Dust"},
 {id:"flare",icon:"☼",name:"Solar Flare",cost:180,type:"crit",power:2,desc:"Raises critical harvest chance"},
 {id:"core",icon:"◆",name:"Iron Heart",cost:1200,type:"auto",power:7,desc:"A dense, tireless planetary core"},
 {id:"tectonics",icon:"⬡",name:"World Forge",cost:9000,type:"auto",power:50,desc:"Moves continents without rest"},
 {id:"civilization",icon:"⌁",name:"Star Choir",cost:80000,type:"auto",power:480,desc:"A civilization gathers Star Dust"},
 {id:"loom",icon:"∞",name:"Quantum Loom",cost:750000,type:"auto",power:12000,desc:"Weaves probability into matter"},
 {id:"nebula",icon:"✺",name:"Nebula Heart",cost:9000000,type:"auto",power:160000,desc:"Births stars in clouds of dust"},
 {id:"epoch",icon:"⌛",name:"Epoch Engine",cost:140000000,type:"auto",power:2400000,desc:"Turns deep time into power"},
 {id:"crown",icon:"♜",name:"Galactic Crown",cost:3000000000,type:"auto",power:50000000,desc:"Commands a spiral of suns"},
 {id:"quasar",icon:"✹",name:"Quasar Throne",cost:90000000000,type:"auto",power:1400000000,desc:"Feeds upon a brilliant nucleus"},
 {id:"reality",icon:"◇",name:"Reality Root",cost:4000000000000,type:"auto",power:70000000000,desc:"Anchors creation to your will"},
 {id:"eternity",icon:"◈",name:"Eternity Furnace",cost:300000000000000,type:"auto",power:6000000000000,desc:"Burns the final age as fuel"},
 {id:"omniverse",icon:"✧",name:"Omniverse Seed",cost:20000000000000000,type:"auto",power:500000000000000,desc:"Germinates adjacent realities"}
];
function achievements(){const chapter=activeChapter(),scale=chapterScale(),names=chapter.seals,stage=state.stage||0;return[
 {id:`${stage}-first`,name:names[0],desc:"Harvest the core once.",test:s=>s.clicks>=1,reward:1+stage},
 {id:`${stage}-matter`,name:names[1],desc:`Create ${format(500*scale)} lifetime Star Dust.`,test:s=>s.totalEssence>=500*scale,reward:2+stage},
 {id:`${stage}-era2`,name:names[2],desc:`Reach ${chapter.eras[2]}.`,test:s=>s.maxEra>=2,reward:3+stage},
 {id:`${stage}-flow`,name:names[3],desc:`Reach ${format(100*scale)} Star Dust per second.`,test:s=>s.autoRate>=100*scale,reward:4+stage},
 {id:`${stage}-era4`,name:names[4],desc:`Reach ${chapter.eras[4]}.`,test:s=>s.maxEra>=4,reward:6+stage},
 {id:`${stage}-complete`,name:names[5],desc:`Complete ${chapter.name}.`,test:s=>s.totalEssence>=stageGoal(),reward:10+stage*2}
]}
const missions=[
 {name:"Awaken the core",desc:"Tap the core 25 times.",field:"clicks",target:25,reward:25},
 {name:"Gathering gravity",desc:"Create 750 lifetime Star Dust.",field:"totalEssence",target:750,reward:180},
 {name:"A world that moves",desc:"Reach 30 Star Dust per second.",field:"autoRate",target:30,reward:500},
 {name:"Feed the horizon",desc:"Create 15,000 lifetime Star Dust.",field:"totalEssence",target:15000,reward:4000},
 {name:"The green promise",desc:"Reach Verdant Bloom.",field:"maxEra",target:3,reward:18000},
 {name:"A million grains",desc:"Create 1 million lifetime Star Dust.",field:"totalEssence",target:1e6,reward:180000},
 {name:"An engine of suns",desc:"Reach 1 million Star Dust per second.",field:"autoRate",target:1e6,reward:3e6},
 {name:"Catch the wanderer",desc:"Catch a rare passing comet.",field:"cometsCaught",target:1,reward:12e6},
 {name:"Galactic treasury",desc:"Create 1 billion lifetime Star Dust.",field:"totalEssence",target:1e9,reward:250e6},
 {name:"The trillionth spark",desc:"Create 1 trillion lifetime Star Dust.",field:"totalEssence",target:1e12,reward:80e9},
 {name:"Beyond mortal counting",desc:"Create 1 quadrillion lifetime Star Dust.",field:"totalEssence",target:1e15,reward:90e12},
 {name:"A number without end",desc:"Create 1 quintillion lifetime Star Dust.",field:"totalEssence",target:1e18,reward:75e15}
];
const defaultState={essence:0,totalEssence:0,autoRate:0,clickPower:1,critChance:0,eraIndex:0,maxEra:0,stage:0,upgradesOwned:{},aether:0,rebirthCount:0,clicks:0,cometsCaught:0,claimed:[],missionIndex:0,buyAmount:1,lastTick:Date.now(),nextComet:Date.now()+120000+Math.random()*120000};
let state=load(),toastTimer,cometTimer;
let upgradeSignature="",achievementSignature="";
const $=id=>document.getElementById(id);
function load(){try{const raw=JSON.parse(localStorage.getItem(SAVE_KEY));return raw?{...defaultState,...raw,upgradesOwned:{...(raw.upgradesOwned||{})},claimed:[...(raw.claimed||[])]}:{...defaultState};}catch{return {...defaultState}}}
function save(){state.lastTick=Date.now();localStorage.setItem(SAVE_KEY,JSON.stringify(state))}
const numberTiers=[[1e3,"K"],[1e6,"M"],[1e9,"B"],[1e12,"T"],[1e15,"Qa"],[1e18,"Qi"],[1e21,"Sx"],[1e24,"Sp"],[1e27,"Oc"],[1e30,"No"],[1e33,"Dc"],[1e36,"Ud"],[1e39,"Dd"],[1e42,"Td"],[1e45,"Qad"],[1e48,"Qid"],[1e51,"Sxd"],[1e54,"Spd"],[1e57,"Ocd"],[1e60,"Nod"],[1e63,"Vg"],[1e66,"Uvg"],[1e69,"Dvg"],[1e72,"Tvg"]];
function format(n){if(!Number.isFinite(n))return"∞";const abs=Math.abs(n);if(abs<1000)return Math.floor(n).toLocaleString();let tier=numberTiers[0];for(const candidate of numberTiers){if(abs<candidate[0])break;tier=candidate}const value=n/tier[0],digits=value>=100?0:value>=10?1:2;return `${value.toFixed(digits)} ${tier[1]}`}
function activeChapter(){return chapters[Math.min(state.stage||0,chapters.length-1)]}
function chapterScale(){return Math.pow(10,state.stage||0)}
function stageGoal(){return eras[eras.length-1].min*chapterScale()}
function activeEras(){const chapter=activeChapter(),scale=chapterScale();return eras.map((era,i)=>({...era,name:chapter.eras[i],min:era.min*scale,kicker:`CHAPTER ${(state.stage||0)+1} · ${chapter.name.toUpperCase()}`}))}
function multiplier(){return 1+state.aether*.05}
function rates(){let auto=0,click=1,crit=0;for(const u of upgrades){const n=state.upgradesOwned[u.id]||0;if(u.type==="auto")auto+=u.power*n;if(u.type==="click")click+=n;if(u.type==="crit")crit+=u.power*n}state.autoRate=auto*multiplier();state.clickPower=click;state.critChance=Math.min(35,crit)}
function unitCost(u,count){return Math.floor(u.cost*chapterScale()*Math.pow(1.38,count))}
function purchasePlan(u){let count=state.upgradesOwned[u.id]||0,total=0,qty=0,limit=state.buyAmount===Infinity?250:state.buyAmount;while(qty<limit){const cost=unitCost(u,count+qty);if(!Number.isFinite(cost)||total+cost>state.essence)break;total+=cost;qty++}return{qty,total,next:unitCost(u,count)}}
function formatEffect(n){return Math.abs(n)<1000?Number(n.toFixed(2)).toLocaleString():format(n)}
function upgradeEffect(u){if(u.type==="click")return"Each upgrade adds exactly +1 Star Dust per click";if(u.type==="crit")return`Each upgrade adds +${u.power}% critical chance (max 35%)`;return`Each upgrade adds +${formatEffect(u.power*multiplier())} Star Dust per second`}
function buy(id){const u=upgrades.find(x=>x.id===id),plan=purchasePlan(u);if(!plan.qty)return;state.essence-=plan.total;state.upgradesOwned[id]=(state.upgradesOwned[id]||0)+plan.qty;rates();update();save()}
function harvest(e){const crit=Math.random()*100<state.critChance,gain=state.clickPower*(crit?5:1);state.essence+=gain;state.totalEssence+=gain;state.clicks++;spawn(e.clientX||innerWidth/2,e.clientY||innerHeight/2,`${crit?"CRITICAL ":""}+${format(gain)}`);const b=$("planetButton");b.classList.remove("harvest");void b.offsetWidth;b.classList.add("harvest");update()}
function spawn(x,y,text){const p=document.createElement("span");p.className="particle";p.textContent=text;p.style.left=x+"px";p.style.top=y+"px";document.body.append(p);setTimeout(()=>p.remove(),760)}
function log(text){$("eventLog").textContent=text}
function toast(text){const el=$("toast");el.textContent=text;el.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove("show"),2200)}
function currentEra(){let idx=0;activeEras().forEach((e,i)=>{if(state.totalEssence>=e.min)idx=i});return idx}
function renderEra(force=false){const chapter=activeChapter(),stageEras=activeEras(),idx=currentEra(),era=stageEras[idx];$("chapterLabel").textContent=`CHAPTER ${(state.stage||0)+1} · ${chapter.name}`;if(idx!==state.eraIndex||force){const changed=idx>state.eraIndex;state.eraIndex=idx;state.maxEra=Math.max(state.maxEra,idx);$("eraImage").src=era.image;$("eraImage").alt=era.alt;$("eraName").textContent=era.name;$("eraKicker").textContent=era.kicker;$("eraDesc").textContent=era.desc;$("planetButton").setAttribute("aria-label",`Harvest Star Dust from ${era.name}`);rates();if(changed){toast(`${era.name} awakened`);log(`A new era begins: ${era.name}.`)}}const next=stageEras[idx+1];if(next){const base=era.min,progress=(state.totalEssence-base)/(next.min-base);$("eraProgressLabel").textContent=`Next: ${next.name}`;$("eraProgressValue").textContent=`${format(state.totalEssence)} / ${format(next.min)}`;$("eraProgressBar").style.width=Math.min(100,progress*100)+"%"}else{$("eraProgressLabel").textContent=`Complete ${chapter.name}`;$("eraProgressValue").textContent=`${format(state.totalEssence)} / ${format(stageGoal())}`;$("eraProgressBar").style.width=Math.min(100,state.totalEssence/stageGoal()*100)+"%"}}
function renderUpgrades(){const chapter=activeChapter(),signature=upgrades.map(u=>{const p=purchasePlan(u);return `${u.id}:${state.upgradesOwned[u.id]||0}:${p.qty}:${p.total}:${state.essence>=p.next}`}).join("|")+":"+state.buyAmount+":"+state.stage+":"+state.aether;if(signature===upgradeSignature)return;upgradeSignature=signature;$("upgradeContainer").innerHTML=upgrades.map((u,i)=>{const count=state.upgradesOwned[u.id]||0,plan=purchasePlan(u),price=plan.qty?plan.total:plan.next,name=chapter.upgrades[i];return `<button class="upgrade" data-buy="${u.id}" onclick="buy('${u.id}')" ${state.essence<plan.next?"disabled":""}><span class="upgrade-icon">${u.icon}</span><span class="upgrade-copy"><strong>${name} · ${count}</strong><span>${upgradeEffect(u)}</span></span><span class="upgrade-price"><strong>${format(price)}</strong><small>${state.buyAmount===Infinity?`MAX ${plan.qty}`:state.buyAmount>1?`BUY ${plan.qty}`:"STAR DUST"}</small></span></button>`}).join("")}
function renderMission(){const done=state.missionIndex>=missions.length,m=missions[Math.min(state.missionIndex,missions.length-1)],current=done?m.target:Math.min(m.target,state[m.field]||0);$("missionName").textContent=done?"Prophecies fulfilled":m.name;$("missionDesc").textContent=done?"Ascend to begin the cycle with greater power.":m.desc;$("missionProgress").textContent=done?"COMPLETE":`${format(current)} / ${format(m.target)}`;$("missionReward").textContent=done?"":`+${format(m.reward)} Star Dust`;$("missionBar").style.width=(done?100:current/m.target*100)+"%";if(!done&&current>=m.target){state.essence+=m.reward;state.totalEssence+=m.reward;state.missionIndex++;toast(`Prophecy fulfilled · +${format(m.reward)} Star Dust`);renderMission()}}
function renderAchievements(){const list=achievements(),status=list.map(a=>`${a.id}:${a.test(state)}:${state.claimed.includes(a.id)}`).join("|");if(status===achievementSignature)return;achievementSignature=status;let ready=0;$("achievementList").innerHTML=list.map(a=>{const claimed=state.claimed.includes(a.id),complete=a.test(state);if(complete&&!claimed)ready++;return `<article class="achievement ${claimed?"claimed":complete?"ready":""}"><small>+${a.reward} AETHER</small><h2>${a.name}</h2><p>${a.desc}</p><button data-claim="${a.id}" onclick="claim('${a.id}')" ${!complete||claimed?"disabled":""}>${claimed?"RECORDED":complete?"CLAIM SEAL":"LOCKED"}</button></article>`}).join("");$("claimBadge").hidden=!ready}
function claim(id){const a=achievements().find(x=>x.id===id);if(!a||state.claimed.includes(id)||!a.test(state))return;state.claimed.push(id);state.aether+=a.reward;rates();toast(`Seal claimed · +${a.reward} Aether`);update();save()}
function anomaly(){const comet=$("cometButton");if(!comet.hidden||Date.now()<state.nextComet)return;state.nextComet=Date.now()+240000+Math.random()*240000;comet.style.setProperty("--comet-top",`${18+Math.random()*49}%`);comet.hidden=false;comet.style.animation="none";void comet.offsetWidth;comet.style.animation="";clearTimeout(cometTimer);cometTimer=setTimeout(()=>{if(comet.hidden)return;comet.hidden=true;log("A rare comet escaped beyond the horizon.");save()},9500);save()}
function catchComet(e){const comet=$("cometButton");if(comet.hidden)return;clearTimeout(cometTimer);comet.hidden=true;state.cometsCaught=(state.cometsCaught||0)+1;const reward=Math.max(500,state.autoRate*60,state.clickPower*100);state.essence+=reward;state.totalEssence+=reward;spawn(e.clientX||innerWidth/2,e.clientY||innerHeight/2,`COMET +${format(reward)}`);toast(`Rare comet caught · +${format(reward)}`);log(`Comet ${state.cometsCaught} was caught before it crossed the horizon.`);update();save()}
function rewardForRise(){return state.totalEssence>=stageGoal()&&state.maxEra>=4?5+(state.stage||0)*3:0}
function renderRise(){const reward=rewardForRise(),remaining=Math.max(0,stageGoal()-state.totalEssence),next=chapters[Math.min((state.stage||0)+1,chapters.length-1)];$("aetherDisplay").textContent=format(state.aether);$("aetherRewardDisplay").textContent=format(reward);$("aetherTopDisplay").textContent=format(state.aether);$("nextMultiplier").textContent=(1+(state.aether+reward)*.05).toFixed(2)+"×";$("rebirthButton").disabled=reward<1;$("rebirthButton").textContent=reward?`ASCEND TO ${next.name.toUpperCase()}`:"FINISH THIS CHAPTER FIRST";$("rebirthRequirement").textContent=reward<1?`Complete ${activeChapter().name}: ${format(remaining)} Star Dust remaining.`:`Begin ${next.name} with zero Star Dust, zero Flow and new upgrades.`}
function ascend(){const reward=rewardForRise();if(reward<1)return;const nextStage=(state.stage||0)+1;state={essence:0,totalEssence:0,autoRate:0,clickPower:1,critChance:0,eraIndex:0,maxEra:0,stage:nextStage,upgradesOwned:{},aether:state.aether+reward,rebirthCount:state.rebirthCount+1,clicks:0,cometsCaught:0,claimed:[...state.claimed],missionIndex:0,buyAmount:1,lastTick:Date.now(),nextComet:Date.now()+120000+Math.random()*120000};upgradeSignature="";achievementSignature="";rates();renderEra(true);toast(`${activeChapter().name} begins · +${reward} Aether`);setView("home");update();save()}
function resetStats(){if(!confirm("Reset every Chronos chapter, upgrade, achievement and resource? This cannot be undone."))return;localStorage.removeItem(SAVE_KEY);location.replace(location.pathname+"?reset="+Date.now())}
function update(){renderEra();$("essenceDisplay").textContent=format(state.essence);$("flowDisplay").textContent=format(state.autoRate)+"/s";$("clickPower").textContent="+"+format(state.clickPower);renderUpgrades();renderAchievements();renderRise()}
function setView(name){document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===`view-${name}`));document.querySelectorAll(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.view===name));if(name==="achievements")renderAchievements();if(name==="rebirth")renderRise()}
function offlineGain(){const seconds=Math.min(14400,Math.max(0,(Date.now()-(state.lastTick||Date.now()))/1000));rates();const gain=state.autoRate*seconds;if(gain>=1){state.essence+=gain;state.totalEssence+=gain;setTimeout(()=>toast(`While away · +${format(gain)} Star Dust`),350)}}
$("planetButton").addEventListener("click",harvest);$("buyMode").addEventListener("click",()=>{state.buyAmount=state.buyAmount===1?10:state.buyAmount===10?Infinity:1;$("buyMode").textContent=state.buyAmount===Infinity?"BUY MAX":`BUY ${state.buyAmount}`;upgradeSignature="";renderUpgrades()});$("cometButton").addEventListener("click",catchComet);$("rebirthButton").addEventListener("click",ascend);$("resetStatsButton").addEventListener("click",resetStats);document.addEventListener("keydown",e=>{if(e.code==="Space"&&document.querySelector("#view-home.active")&&!e.repeat&&!e.target.closest("button,input,select,textarea")){e.preventDefault();harvest({clientX:innerWidth*.42,clientY:innerHeight*.5})}});
addEventListener("hashchange",()=>setView(location.hash.slice(1)||"home"));
offlineGain();rates();renderEra(true);update();setView(location.hash.slice(1)||"home");setInterval(()=>{const delta=Math.min(.25,(Date.now()-state.lastTick)/1000);state.lastTick=Date.now();if(state.autoRate){const gain=state.autoRate*delta;state.essence+=gain;state.totalEssence+=gain}anomaly();update()},250);setInterval(save,8000);addEventListener("pagehide",save);
